### ISSUE TITLE
This is not a issue

### ISSUE THREAD

**Issue by lbq8942** [fpour/DGB#1]
Nice work!

**Comment by lbq8942** [comment]
i have a question, why the dataset downloaded from DG_data/note.txt and Readme.md are different.

**Comment by fpour** [comment]
To ensure long-term access to the datasets, we decided to host them on Zenodo (Digital Library for Open Data by CERN). The access link is "https://zenodo.org/record/7008205#.YwQfPnbMJPa".
The DG_data/note.txt and Readme.md files are updated accordingly.
